version: '3'
services:
  terraria:
    image: yhoths/terraria-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TERRARIA_VERSION: ${TERRARIA_VERSION}
    container_name: 'terraria'
    ports:
      - "${TERRARIA_PORT}:7777"
    expose:
      - "7777"
    environment:
      - TERRARIA_SHUTDOWN_MESSAGE=${TERRARIA_SHUTDOWN_MESSAGE}
      - TERRARIA_AUTOSAVE_INTERVAL=${TERRARIA_AUTOSAVE_INTERVAL}
      - TERRARIA_MOTD=${TERRARIA_MOTD}
      - TERRARIA_PASS=${TERRARIA_PASS}
      - TERRARIA_MAXPLAYERS=${TERRARIA_MAXPLAYERS}
      - TERRARIA_WORLDNAME=${TERRARIA_WORLDNAME}
      - TERRARIA_WORLDSIZE=${TERRARIA_WORLDSIZE}
      - TERRARIA_WORLDSEED=${TERRARIA_WORLDSEED}
      - TERRARIA_DIFFICULTY=${TERRARIA_DIFFICULTY}
      - TERRARIA_NPCSTREAM=${TERRARIA_NPCSTREAM}
      - TERRARIA_USECONFIGFILE=${TERRARIA_USECONFIGFILE}

    volumes:
      - "${TERRARIA_DATA_PATH}:/root/.local/share/Terraria"
      - "${TERRARIA_CONFIG_PATH:-./serverconfig.txt}:/root/terraria-server/serverconfig.txt:ro"
    tty: true
    stdin_open: true